In [166]:
import seaborn as sns
import pandas as pd

In [167]:
df = sns.load_dataset('titanic')

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [169]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [170]:
print(df.age.value_counts())

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: age, Length: 88, dtype: int64


In [171]:
print(df.deck.value_counts())

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64


In [172]:
df[['class','deck']] = df[['class','deck']].astype('object')

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [174]:
df[['class','deck']].head()

class deck
0  Third  NaN
1  First    C
2  Third  NaN
3  First    C
4  Third  NaN

In [175]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
enc = OrdinalEncoder()
enc2 = OneHotEncoder()
X = pd.DataFrame([['Male', 1], ['Female', 3], ['Female', 2]])
enc.fit(X)

enc.categories_

enc.transform([['Female', 3], ['Male', 1]])

array([[0., 2.],
       [1., 0.]])

In [22]:
enc2.fit_transform(X).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [35]:
X.columns = ['a','b']
X

a  b
0    Male  1
1  Female  3
2  Female  2

In [39]:
X.a = enc.fit_transform(X.a.values.reshape(-1,1))

In [40]:
X

a  b
0  1.0  1
1  0.0  3
2  0.0  2

In [41]:
import numpy as np
x = np.array([[[0], [1], [2]]])
x

array([[[0],
        [1],
        [2]]])

In [45]:
np.squeeze([['Female', 3], ['Male', 1]]).shape

(2, 2)

In [44]:
np.array([['Female', 3], ['Male', 1]]).shape

(2, 2)

In [57]:
df.isna().sum(axis= 1)

0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [176]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [77]:
df.survived.loc[1]

1

In [86]:
df.survived.loc[df.survived.notna()]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [92]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [94]:
cat_col = ['sex','embarked','class','who','adult_male','deck', 'embark_town', 'alive', 'alone']

In [184]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import KNNImputer
ode = OrdinalEncoder()
KNN_imp = KNNImputer()

def encodeCol(col):
    not_null = col.loc[col.notna()]
    temp_encoded = ode.fit_transform(not_null.values.reshape(-1,1))
    col.loc[col.notna()] = np.squeeze(temp_encoded)
    return col

In [185]:
for columns in cat_col:
    df[columns] = encodeCol(df[columns])

C:\Users\anuna\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\anuna\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\anuna\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
 

In [187]:
df

survived  pclass  sex   age  sibsp  parch     fare embarked  class  who  \
0           0       3  1.0  22.0      1      0   7.2500        2    2.0  1.0   
1           1       1  0.0  38.0      1      0  71.2833        0    0.0  2.0   
2           1       3  0.0  26.0      0      0   7.9250        2    2.0  2.0   
3           1       1  0.0  35.0      1      0  53.1000        2    0.0  2.0   
4           0       3  1.0  35.0      0      0   8.0500        2    2.0  1.0   
..        ...     ...  ...   ...    ...    ...      ...      ...    ...  ...   
886         0       2  1.0  27.0      0      0  13.0000        2    1.0  1.0   
887         1       1  0.0  19.0      0      0  30.0000        2    0.0  2.0   
888         0       3  0.0   NaN      1      2  23.4500        2    2.0  2.0   
889         1       1  1.0  26.0      0      0  30.0000        0    0.0  1.0   
890         0       3  1.0  32.0      0      0   7.7500        1    2.0  1.0   

     adult_male deck embark_town  alive  alone  
0           1.0  NaN           2    0.0    0.0  
1           0.0    2           0    1.0    0.0  
2           0.0  NaN           2    1.0    1.0  
3           0.0    2           2    1.0    0.0  
4           1.0  NaN           2    0.0    1.0  
..          ...  ...         ...    ...    ...  
886         1.0  NaN           2    0.0    1.0  
887         0.0    1           2    1.0    1.0  
888         0.0  NaN           2    0.0    0.0  
889         1.0    2           0    1.0    1.0  
890         1.0  NaN           1    0.0    1.0  

[891 rows x 15 columns]

In [191]:
pd.DataFrame(KNN_imp.fit_transform(df), columns=df.columns)

survived  pclass  sex   age  sibsp  parch     fare  embarked  class  who  \
0         0.0     3.0  1.0  22.0    1.0    0.0   7.2500       2.0    2.0  1.0   
1         1.0     1.0  0.0  38.0    1.0    0.0  71.2833       0.0    0.0  2.0   
2         1.0     3.0  0.0  26.0    0.0    0.0   7.9250       2.0    2.0  2.0   
3         1.0     1.0  0.0  35.0    1.0    0.0  53.1000       2.0    0.0  2.0   
4         0.0     3.0  1.0  35.0    0.0    0.0   8.0500       2.0    2.0  1.0   
..        ...     ...  ...   ...    ...    ...      ...       ...    ...  ...   
886       0.0     2.0  1.0  27.0    0.0    0.0  13.0000       2.0    1.0  1.0   
887       1.0     1.0  0.0  19.0    0.0    0.0  30.0000       2.0    0.0  2.0   
888       0.0     3.0  0.0  32.8    1.0    2.0  23.4500       2.0    2.0  2.0   
889       1.0     1.0  1.0  26.0    0.0    0.0  30.0000       0.0    0.0  1.0   
890       0.0     3.0  1.0  32.0    0.0    0.0   7.7500       1.0    2.0  1.0   

     adult_male  deck  embark_town  alive  alone  
0           1.0   4.6          2.0    0.0    0.0  
1           0.0   2.0          0.0    1.0    0.0  
2           0.0   5.0          2.0    1.0    1.0  
3           0.0   2.0          2.0    1.0    0.0  
4           1.0   3.6          2.0    0.0    1.0  
..          ...   ...          ...    ...    ...  
886         1.0   4.4          2.0    0.0    1.0  
887         0.0   1.0          2.0    1.0    1.0  
888         0.0   4.6          2.0    0.0    0.0  
889         1.0   2.0          0.0    1.0    1.0  
890         1.0   4.2          1.0    0.0    1.0  

[891 rows x 15 columns]

In [192]:
df2 = pd.DataFrame({'num_legs': [2, 4, 8, 0],

                   'num_wings': [2, 0, 0, 0],

                   'num_specimen_seen': [10, 2, 1, 8]},

                  index=['falcon', 'dog', 'spider', 'fish'])

In [193]:
df2

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [194]:
df2 = sns.load_dataset('iris')

In [196]:
df2.species.value_counts()

virginica     50
versicolor    50
setosa        50
Name: species, dtype: int64

In [202]:
from sklearn.preprocessing import OneHotEncoder
df2 = sns.load_dataset('iris')
ohe = OneHotEncoder(drop='first')
ttt = ohe.fit_transform(df2['species'].values.reshape(-1,1))

In [203]:
ttt.toarray()

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.